version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -y aws-cdk@2.70.0
  build:
    commands:
      - npm run build
      - cdk synth
cache:
  paths:
    - 'node_modules/**/*'
#artifacts:
#  files:
#    - '**/*'